#ifndef RESOURCE_H
#define RESOURCE_H

#define IDB_HORSE                       101
#define IDB_TEMP                        102
#define IDB_ADINA	                    103
#define IDB_ANKKA	                    104
#define IDB_ARKK	                    105
#define IDB_ARTSARIIV	                106
#define IDB_BERG	                    107
#define IDB_BONESKINNER	                108
#define IDB_BROKEN_KING	                109
#define IDB_CAIRN	                    110
#define IDB_CAPTAIN_MAI_TRIN	        111
#define IDB_CERUS_AND_DEIMOS	        112
#define IDB_CERUS	                    113
#define IDB_CONJURED_AMALGAMATE	        114
#define IDB_DAGDA	                    115
#define IDB_DEIMOS	                    116
#define IDB_DHUUM	                    117
#define IDB_EATER_OF_SOULS	            118
#define IDB_ELEMENTAL_AI_DARK	        119
#define IDB_ELEMENTAL_AI_LIGHT_AND_DARK	120
#define IDB_ELEMENTAL_AI_LIGHT	        121
#define IDB_ENSOLYSS	                122
#define IDB_EPARCH	                    123
#define IDB_ESCORT	                    124
#define IDB_EYES_OF_FATE	            125
#define IDB_FRAENIR_OF_JORMAG	        126
#define IDB_FREEZIE	                    127
#define IDB_GORSEVAL	                128
#define IDB_HARVEST_TEMPLE	            129
#define IDB_ICEBROOD_CONSTRUCT	        131
#define IDB_KEEP_CONSTRUCT	            132
#define IDB_KENUTT	                    133
#define IDB_KODANS	                    134
#define IDB_MAMA	                    135
#define IDB_MATTHIAS	                136
#define IDB_MINISTER_LI	                137
#define IDB_MURSAAT_OVERSEER	        138
#define IDB_NARELLA	                    139
#define IDB_NIKARE	                    140
#define IDB_QADIM	                    141
#define IDB_QADIM_THE_PEERLESS	        142
#define IDB_RIVER_OF_SOULS	            143
#define IDB_SABETHA	                    144
#define IDB_SABIR	                    145
#define IDB_SAMAROG	                    146
#define IDB_SIAX	                    147
#define IDB_SKORVALD	                148
#define IDB_SLOTHASOR	                149
#define IDB_SOULLESS_HORROR	            150
#define IDB_TWISTED_CASTLE	            152
#define IDB_VALE_GUARDIAN	            153
#define IDB_WATCHKNIGHT_MARK_II	        154
#define IDB_WHISPER_OF_JORMAG	        155
#define IDB_XERA	                    156
#define IDB_ZANE	                    157

#endif //RESOURCE_H
